tfe_url: https://tfe.sbx.hashidemos.io
varset_name: global-proxy-override
varset_description: Global proxy override varset for proxy
organizations:
 - org-001
 - phoebe-test
 - doesnt-exist
varset_vars:
  - key: proxy
    value: https://proxy.example.com:8080
    description: Proxy for this and that
    sensitive: false
    category: terraform
    hcl: false
  - key: key_example
    value: 61e400d5ccffb3782f215344481e6c82